//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantReview
    {
        public int RestaurantReviewID { get; set; }
        public int RestaurantID { get; set; }
        public string ReviewName { get; set; }
        public string ReviewContent { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<System.DateTime> ReviewDateTime { get; set; }
    }
}
