//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantTask
    {
        public int RestaurantTaskID { get; set; }
        public Nullable<int> RestaurantID { get; set; }
        public Nullable<System.DateTime> TaskDate { get; set; }
        public string TaskSubject { get; set; }
        public string TaskDescription { get; set; }
    }
}
